//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RezidanslarApiUyg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gorevler
    {
        public int gorevNo { get; set; }
        public string gorevAdi { get; set; }
        public Nullable<int> gorevSuresi { get; set; }
        public string aciklama { get; set; }
    }
}
