//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RezidanslarApiUyg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        public int personelNo { get; set; }
        public string personelAdi { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
    }
}
