//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RezidanslarApiUyg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plazalar
    {
        public int plazaNo { get; set; }
        public string plazaAdi { get; set; }
        public Nullable<int> BlokSayi { get; set; }
        public string Sehir { get; set; }
        public string Semt { get; set; }
        public string Adres { get; set; }
    }
}
