//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RezidaslarMVCkatman.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Kullanicilar
    {
        public int kullaniciNo { get; set; }
        [Required(ErrorMessage = "Zorunlu Alan!")]
        [Display(Name = "Kullanýcý Adý")]
        public string kullaniciAdi { get; set; }

        [Required(ErrorMessage = "Zorunlu Alan!")]
        [Display(Name = "Þifre")]   
        [DataType(DataType.Password)]
        public string sifre { get; set; }

        [Required(ErrorMessage = "Zorunlu Alan!")]
        [Display(Name = "Þifre Tekrarý")]
        [DataType(DataType.Password)]
        [NotMapped]
        [Compare("sifre", ErrorMessage = "Þifreler Uyuþmuyor! Tekrar Deneyin!")]
        public string MatchSifre { get; set; }
    }
}
